### ISSUE TITLE
Exception: Request failed for https://api.doxey.io returned code 400

### ISSUE THREAD

**Issue by Jacobvdb** [floreysoft/doxey-client-gappsscript-sample#1]
I ran the example and it gave the following error: 

Exception: Request failed for https://api.doxey.io returned code 400. Truncated server response: {"code":400,"message":"transformation failed (4)","exception":"org.jodconverter.office.OfficeException","details":"Task failed"} (use muteHttpExceptions option to examine full response)
testMerge	

Maybe you can have a look at it

**Comment by alexbrickwedde** [comment]
Thanks for your message. It was a problem on the server, which is solved now.
